default: &default
  adapter: mysql2
  host: localhost
  port: 3306

development:
  <<: *default
  database: compote_development
  username: root

test:
  <<: *default
  database: compote_test
  username: root
