default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_general_ci

development:
  <<: *default
  database: compote_development
  username: root

test:
  <<: *default
  database: compote_test
  username: root
