# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a88c889be1473c44e3a0cfe1896281dc8b3fa201aad04ce431e921db40e3e01338fbfa70fc61841ac621dcb057ee14124bfdc29752fc962788a72ca794f8724

test:
  secret_key_base: ec676fe4987200d69e1f981e903452b6e7f82fe2caa43ecffff5f4c43d310b83ecbce33476f6d007f6b46604c3a075fb09fe8f6bf3983abde63f3a0506f91120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
